[book]
title = "Lithair Documentation"
authors = ["Yoan Roblet (Arcker)"]
description = "Data-First Rust framework for high-performance backends"
language = "en"
src = "."

[build]
build-dir = "../../lithair-website/public/docs"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/lithair/lithair"
edit-url-template = "https://github.com/lithair/lithair/edit/main/docs/{path}"
site-url = "/docs/"
additional-css = ["theme/custom.css"]
additional-js = ["mermaid-init.js"]
no-section-label = false

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = false
copyable = true
copy-js = true
runnable = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true
